import PropTypes from 'prop-types';
import React, { useState } from 'react';
import { Form, Input, Row, Col, Tooltip, Checkbox } from 'antd';
import { CopyOutlined, InfoCircleOutlined } from '@ant-design/icons';
import { validateDomains, validateSsoUrl, validatePemOrDerCertFile, validatePkcs12File } from '../../../../../utils/sso-integration-field-validator';
import { SAML_ACS_URL, SAML_ENTITY_ID } from '../../../../../constants/SsoConstants';
import TestConnectionPanel from './TestConnectionPanel';

const fieldLabel    = { fontSize: 13, fontWeight: 400, color: '#595959' };
const readOnlyStyle = { background: '#f5f5f5', borderColor: '#d9d9d9', color: '#1a1a2e', borderRadius: 6 };

const sectionHeaderStyle = {
  fontSize: 13,
  fontWeight: 600,
  color: '#1a1a2e',
  marginBottom: 10,
  marginTop: 4,
  paddingBottom: 6,
  borderBottom: '1px solid #f0f0f0',
  display: 'block',
};

const copyHintStyle = {
  fontSize: 11,
  color: '#8c8c8c',
  marginBottom: 14,
  display: 'block',
};

const RequiredMark = () => <span style={{ color: '#ff4d4f' }}>{' *'}</span>;  // fix: ambiguous spacing (S6772)

const SamlConfigForm = ({
  signAuthn,
  onSignAuthnChange,
  onFileChange,
  isTestReady,
  testLoading,
  testResult,
  onTest,
}) => {
  const [copiedAcs, setCopiedAcs]       = useState(false);
  const [copiedEntity, setCopiedEntity] = useState(false);

  return (
    <>
      {/* ── SECTION 1: Zebra DNA Generated Values (Read-Only / Copy) ── */}
      <span style={sectionHeaderStyle}>
        Zebra DNA Configuration Values
        <Tooltip title="These values are generated by Zebra DNA. Copy and paste them into your Microsoft Entra Enterprise Application configuration.">
          <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
        </Tooltip>
      </span>
      <span style={copyHintStyle}>
        Copy the values below and enter them in your Microsoft Entra Enterprise Application settings.
      </span>

      <Form.Item
        label={
          <span style={fieldLabel}>
            ACS URL (Assertion Consumer Service URL)
            <Tooltip title="Copy this URL and paste it into the 'Reply URL (Assertion Consumer Service URL)' field in your Entra Enterprise Application.">
              <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
            </Tooltip>
          </span>
        }
        style={{ marginBottom: 12 }}
      >
        <Input
          readOnly
          value={SAML_ACS_URL}
          style={readOnlyStyle}
          suffix={
            <Tooltip title={copiedAcs ? 'Copied!' : 'Copy ACS URL'}>
              <CopyOutlined
                onClick={() => { navigator.clipboard.writeText(SAML_ACS_URL); setCopiedAcs(true); setTimeout(() => setCopiedAcs(false), 2000); }}
                style={{ color: copiedAcs ? '#36B37E' : '#0073E6', cursor: 'pointer' }}
              />
            </Tooltip>
          }
        />
      </Form.Item>

      <Form.Item
        label={
          <span style={fieldLabel}>
            Entity ID
            <Tooltip title="Copy this value and paste it into the 'Identifier (Entity ID)' field in your Entra Enterprise Application.">
              <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
            </Tooltip>
          </span>
        }
        style={{ marginBottom: 20 }}
      >
        <Input
          readOnly
          value={SAML_ENTITY_ID}
          style={readOnlyStyle}
          suffix={
            <Tooltip title={copiedEntity ? 'Copied!' : 'Copy Entity ID'}>
              <CopyOutlined
                onClick={() => { navigator.clipboard.writeText(SAML_ENTITY_ID); setCopiedEntity(true); setTimeout(() => setCopiedEntity(false), 2000); }}
                style={{ color: copiedEntity ? '#36B37E' : '#0073E6', cursor: 'pointer' }}
              />
            </Tooltip>
          }
        />
      </Form.Item>

      {/* ── SECTION 2: Entra Configuration (User Input) ── */}
      <span style={{ ...sectionHeaderStyle, marginTop: 8 }}>
        Microsoft Entra Configuration
        <Tooltip title="Enter the values from your Microsoft Entra Enterprise Application SAML configuration.">
          <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
        </Tooltip>
      </span>

      <Form.Item
        label={
          <span style={fieldLabel}>
            IdP SSO URL<RequiredMark />
            <Tooltip title="Found in Entra Enterprise Application → Single sign-on → SAML Signing Certificate section. Copy the 'Login URL' value.">
              <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
            </Tooltip>
          </span>
        }
        name="sso_url"
        rules={[{ validator: validateSsoUrl('saml') }]}
        style={{ marginBottom: 16 }}
      >
        <Input placeholder="https://login.microsoftonline.com/{tenant-id}/saml2" />
      </Form.Item>

      <Form.Item
        label={
          <span style={fieldLabel}>
            Application (Client) ID<RequiredMark />
            <Tooltip title="Found in Entra Enterprise Application → Overview. Copy the 'Application (client) ID' value.">
              <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
            </Tooltip>
          </span>
        }
        name="app_id"
        rules={[{ required: true, message: 'Application ID is required' }]}
        style={{ marginBottom: 16 }}
      >
        <Input placeholder="00000000-0000-0000-0000-000000000000" />
      </Form.Item>

      <Form.Item
        label={
          <span style={fieldLabel}>
            Microsoft Entra Tenant Domain<RequiredMark />
            <Tooltip title="Enter the verified domain(s) registered in your Microsoft Entra tenant (e.g. contoso.com). Users signing in with these domains will be routed to your Entra SSO login. Separate multiple domains with a comma.">
              <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
            </Tooltip>
          </span>
        }
        name="entra_domain"
        rules={[{ validator: validateDomains }]}
        style={{ marginBottom: 16 }}
      >
        <Input placeholder="contoso.com, subsidiary.com" />
      </Form.Item>

      <Form.Item
        label={
          <span id="saml-cert-label" style={fieldLabel}>
            Entra Signing Certificate (.cer / .cert / .pem)<RequiredMark />
            <Tooltip title="Download the Base64 certificate from Entra Enterprise Application → Single sign-on → SAML Signing Certificate → Download (Certificate Base64).">
              <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
            </Tooltip>
          </span>
        }
        name="saml_cert"
        valuePropName="file"
        getValueFromEvent={(e) => e?.target?.files?.[0]}
        rules={[{
          validator: async (_, file) => {
            if (!file) throw new Error('Certificate is required');
            await validatePemOrDerCertFile(file);
          }
        }]}
        style={{ marginBottom: 16 }}
      >
        <input
          id="saml_cert_file_input"
          type="file"
          accept=".crt,.cert,.pem,.cer"
          style={{ width: '100%', padding: '4px 0' }}
          onChange={(e) => onFileChange('saml_cert', e)}
        />
      </Form.Item>

      <Form.Item
        name="sign_auth"
        valuePropName="checked"
        style={{ marginBottom: signAuthn ? 12 : 16 }}
      >
        <Checkbox onChange={e => onSignAuthnChange(e.target.checked)}>
          <span style={fieldLabel}>
            Sign Authentication Request
            <Tooltip title="Enable this if your Entra Enterprise Application requires signed AuthnRequests. You will need to upload a signing certificate (.pfx/.p12) and its password.">
              <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
            </Tooltip>
          </span>
        </Checkbox>
      </Form.Item>

      {signAuthn && (                                          // fix: removed stray }) (S6766)
        <Row gutter={16}>
          <Col span={12}>
            <Form.Item
              label={
                <span id="saml-signing-cert-label" style={fieldLabel}>
                  Signing Certificate (.pfx / .p12)<RequiredMark />
                  <Tooltip title="Upload the PKCS#12 (.pfx or .p12) certificate used to sign AuthnRequests sent to Entra.">
                    <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
                  </Tooltip>
                </span>
              }
              name="saml_signing_cert"
              valuePropName="file"
              getValueFromEvent={(e) => e?.target?.files?.[0]}
              rules={[{
                validator: async (_, file) => {
                  if (!file) throw new Error('Signing certificate is required');
                  await validatePkcs12File(file);
                }
              }]}
              style={{ marginBottom: 16 }}
            >
              <input
                id="saml_signing_cert_file_input"
                type="file"
                accept=".pfx,.p12"
                style={{ width: '100%', padding: '4px 0' }}
                onChange={(e) => onFileChange('saml_signing_cert', e)}
              />
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item
              label={
                <span style={fieldLabel}>
                  Certificate Password<RequiredMark />
                  <Tooltip title="Enter the password used to protect the signing certificate (.pfx/.p12) file.">
                    <InfoCircleOutlined style={{ color: '#0073E6', fontSize: 13, marginLeft: 6, cursor: 'pointer' }} />
                  </Tooltip>
                </span>
              }
              name="saml_signing_cert_password"
              rules={[{ required: true, message: 'Password required' }]}
              style={{ marginBottom: 16 }}
            >
              <Input.Password />
            </Form.Item>
          </Col>
        </Row>
      )}

      <TestConnectionPanel
        isTestReady={isTestReady}
        testLoading={testLoading}
        testResult={testResult}
        onTest={onTest}
      />
    </>
  );
};

SamlConfigForm.propTypes = {
  signAuthn:         PropTypes.bool.isRequired,
  onSignAuthnChange: PropTypes.func.isRequired,
  onFileChange:      PropTypes.func.isRequired,
  isTestReady:       PropTypes.bool.isRequired,
  testLoading:       PropTypes.bool.isRequired,
  onTest:            PropTypes.func.isRequired,
  testResult: PropTypes.shape({
    status:  PropTypes.string,
    message: PropTypes.string,
  }),
};

export default SamlConfigForm;
